# The port that the server will run on.
server:
  port: 8081

# The name of the application
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #         globalcors:
      #           corsConfigurations:
      #             [ /** ]:
      #               allowedOrigins: /**
      #               allowedMethods: GET,POST,PUT,PATCH,DELETE
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: AuthenticationFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - name: AuthenticationFilter
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/categories/**
          filters:
            - name: AuthenticationFilter
  
  # The URL of the configuration server.
  config:
    import:
      configserver:http://${CONFIG_DOCKER:localhost}:9296
  
  # Exposes the actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: /**
      health:
        enabled: true

## Swagger URL -> http://localhost:8081/webjars/swagger-ui/index.html

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls[0]:
      url: /v3/api-docs
      name: API Gateway Service
      primaryName: API Gateway Service
    urls[1]:
      url: /users/v3/api-docs
      name: User Service
      primaryName: User Service
    urls[2]:
      url: /categories/v3/api-docs
      name: Category Service
      primaryName: Category Service
    urls[3]:
      url: /products/v3/api-docs
      name: Product Service
      primaryName: Product Service
  enable-native-support: true
  api-docs.enabled: true

# The secret key for JSON Web Tokens (JWT).
app.jwt.secret: RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!
