# The port that the server will run on.
server:
  port: 8081

# The name of the application
spring:
  application:
    name: API-GATEWAY

  data:
    mongodb:
      host: localhost
      port: 27017
      database: userDB

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/categories/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/webhook/razorpay, /payments/**

  main:
    web-application-type: reactive

  # The URL of the configuration server.
  config:
    import:
      configserver:http://${CONFIG_DOCKER:localhost}:9296
  
  # Exposes the actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: /**
      health:
        enabled: true

## Swagger URL -> http://localhost:8081/webjars/swagger-ui/index.html

springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs.html
    config-url: /v3/api-docs/swagger-config
    urls[0]:
      url: /v3/api-docs
      name: API Gateway Service
      primaryName: API Gateway Service
    urls[1]:
      url: /users/v3/api-docs
      name: User Service
      primaryName: User Service
    urls[2]:
      url: /categories/v3/api-docs
      name: Category Service
      primaryName: Category Service
    urls[3]:
      url: /products/v3/api-docs
      name: Product Service
      primaryName: Product Service
    urls[4]:
      url: /payments/v3/api-docs
      name: Payment Service
      primaryName: Payment Service
    urls[5]:
      url: /cart/v3/api-docs
      name: Cart Service
      primaryName: Cart Service
  enable-native-support: true
  api-docs.enabled: true

# The secret key for JSON Web Tokens (JWT).
app.jwt.secret: RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!
# One day validity
app.jwt.expiration-in-ms: 86400000
